### ISSUE TITLE
problème python

### ISSUE THREAD

**Issue by dllaurent** [neuhausj/JeedomTools#2]
Bonjour, très bon travail malheureusement je me retrouve coincé.
lorsque je lance le script, il me met bien le message "Started Jeedom-InfluxDB bridge on port  4321".
lors de l'ajout de l’adresse push dans jeedom, j'obtiens un message d'erreur dans la fenêtre du script.

Exception happened during processing of request from ('192.168.1.101', 42410)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "Bridge_Jeedom_InfluxDB.py", line 93, in do_GET
    client.write_points(req)
  File "/usr/lib/python3/dist-packages/influxdb/client.py", line 170, in write_points
    return self.write_points_with_precision(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/influxdb/client.py", line 194, in write_points_with_precision
    status_code=200
  File "/usr/lib/python3/dist-packages/influxdb/client.py", line 124, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.client.InfluxDBClientError: 404: b'404 page not found\n'

Merci d'avance

**Comment by propositionjoe** [comment]
Salut,
Essaie avec une debian 8;
Ça a résolu le soucis d'un ami.
